---
- name: Add ansible tower notifications
  awx.awx.tower_notification:
    channels: "{{ item.channels | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    name: "{{ item.name }}"
    nickname: "{{ item.nickname | default(omit)}}"
    notification_type: "{{ item.notification_type }}"
    organization: "{{ item.organization | default(omit) }}"
    username: "{{ item.username | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    recipients: "{{ item.recipients | default(omit) }}"
    sender: "{{ item.sender| default(omit) }}"
    server: "{{ item.server| default(omit) }}"
    state: "{{ item.state | default('present')}}"
    targets: "{{ item.targets | default(omit) }}"
    use_ssl: "{{ item.use_ssl | default('no') }}"
    use_tls: "{{ item.use_tls | default('no')}}"
  loop: "{{ tower_notifications }}"
